"""Add role field to user table

Revision ID: 9196632d67ac
Revises: 56c7c1dede0f
Create Date: 2025-08-03 08:39:28.956699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9196632d67ac'
down_revision: Union[str, Sequence[str], None] = '56c7c1dede0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Enum('STUDENT', 'TEACHER', name='userrole'), server_default='TEACHER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
